spring:
  application:
    name: cerms-acs

#  datasource:
#    url: jdbc:mysql://localhost:3306/cerms_acs
#    driver-class-name: com.mysql.jdbc.Driver
#    username: SVC_PA2563_APPS_T
#    password: Captiva793Test*
#    testWhileIdle: true
#    validationQuery: SELECT 1

  datasource:
    url: jdbc:sqlserver://USTLCSCSD0046.cosd.co.san-diego.ca.us:1456;databaseName=IAStatisticsDB
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    username: SVC_PA2563_APPS_T
    password: Captiva793Test*
    testWhileIdle: true
    validationQuery: SELECT 1

  # ===============================
  # = JPA / HIBERNATE
  # ===============================
  # Use spring.jpa.properties.* for Hibernate native properties (the prefix is
  # stripped before adding them to the entity manager).

  # Show or not log for each sql query
  jpa:
    show-sql: false
    # Hibernate ddl auto (create, create-drop, update): with "update" the database
    # schema will be automatically updated accordingly to java detail found in
    # the project
    hibernate:
      ddl-auto: none
      use-new-id-generator-mappings: false
      #dialect: org.hibernate.dialect.MySQL5Dialect
      dialect: org.hibernate.dialect.SQLServer2012Dialect
      naming-strategy: org.hibernate.cfg.EJB3NamingStrategy
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      jadira:
        usertype:
          autoRegisterUserTypes: true
      hibernate:
        #dialect: org.hibernate.dialect.MySQL5Dialect
        dialect: org.hibernate.dialect.SQLServer2012Dialect
        cache:
          use_second_level_cache: false8447
          use_query_cache: false
          region:
            factory_class: org.hibernate.cache.ehcache.EhCacheRegionFactory
        format_sql: true

  mail:
    host: mail.sdcounty.ca.gov
    port: 25

  # Other properties
    properties:
      mail:
        debug: false
        transport:
          protocol: smtp
        smtp:
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
          starttls:
            enable: true

server:
  port: 8011

logging:
  level:
    org.springframework.web: INFO
    org.springframework.security: DEBUG
    org.springframework.aop.interceptor: INFO
  file:
    path: ../logs/cermsAcsLogs


cerms:
  acs:
    document:
      poller:
        enabled: true
        schedulerInterval: 0 0/1 * ? * *

    folder:
      path:
        source: '\\ustlsncsd0004.cosd.co.san-diego.ca.us\CERMS_ACS_Test\acsWatchFolder'
        destination:
          success:
            dfs: '\\ustlsncsd0004.cosd.co.san-diego.ca.us\CERMS_ACS_Test\acsProcessedFiles\dfs'
            sd: '\\ustlsncsd0004.cosd.co.san-diego.ca.us\CERMS_ACS_Test\acsProcessedFiles\sd'
            nixie: '\\ustlsncsd0004.cosd.co.san-diego.ca.us\CERMS_ACS_Test\acsProcessedFiles\nixie'
          failure:
            dfs: '\\ustlsncsd0004.cosd.co.san-diego.ca.us\CERMS_ACS_Test\acsFailedFiles\dfs'
            sd: '\\ustlsncsd0004.cosd.co.san-diego.ca.us\CERMS_ACS_Test\acsFailedFiles\sd'
            nixie: '\\ustlsncsd0004.cosd.co.san-diego.ca.us\CERMS_ACS_Test\acsFailedFiles\nixie'
